# syntax=docker/dockerfile:1.3

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt -y update
RUN apt install -y --fix-missing \
    python3-dev \
    python3-pip \
    && apt clean && rm -rf /tmp/* /var/tmp/*

COPY ufo_backend.py ufo_backend.py
COPY requirements.txt requirements.txt
COPY ufo_model.pkl ufo_model.pkl
COPY ufo_label_encoder.pkl ufo_label_encoder.pkl

RUN pip install -U pip
RUN pip install -r requirements.txt

CMD uvicorn ufo_backend:app --host 0.0.0.0 --port 8888
